- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install base packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-docker # to control containers with ansible
      - software-properties-common
      - unattended-upgrades
    state: latest
    update_cache: true

- name: Update the unattended upgrade configuration
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart unattended-upgrades
