- name: Install microk8s as snap
  snap:
    name: microk8s
    channel: latest/stable
    classic: true

- name: Add kubectl as alias to microk8s.kubectl
  community.general.snap_alias:
    name: microk8s.kubectl
    alias: kubectl

- name: Add users to microk8s group
  user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  with_items: "{{ microk8s_users }}"

- name: Enable microk8s addons
  command: microk8s enable {{ item }}
  with_items: "{{ microk8s_addons }}"
  register: microk8s_addon
  failed_when: microk8s_addon.rc > 1
  changed_when: microk8s_addon.rc != 0

- name: Disable microk8s addons
  command: microk8s disable {{ item }}
  with_items: "{{ microk8s_addons_disabled }}"
  register: microk8s_addon
  failed_when: microk8s_addon.rc > 1
  changed_when: microk8s_addon.rc != 0
