apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: media-app-data
        - name: media
          persistentVolumeClaim:
            claimName: media-downloads
      containers:
        - name: radarr
          image: ghcr.io/linuxserver/radarr:4.1.0.6175-ls152
          ports:
            - name: http
              containerPort: 7878
          envFrom:
            - configMapRef:
                name: common-deployment-environment
          volumeMounts:
            - mountPath: /config
              name: app-data
              subPath: radarr
            - mountPath: /data
              name: media

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: radarr

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
spec:
  rules:
    - host: radarr.10.0.0.5.sslip.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: radarr
                port:
                  name: http
