apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8up-operator
resources:
  - helm-rendered.yaml
  - namespace.yml
  - https://github.com/k8up-io/k8up/releases/download/k8up-4.3.0/k8up-crd.yaml
