docker_compose_version: "v2.10.2"
docker_daemon_options:
  log-driver: "journald"
  storage-driver: "overlay2"
docker_users:
  - ubuntu

local_load_balancer_ip: 10.0.0.2
vpn_load_balancer_ip: 100.91.165.113
k8s_load_balancer_ip: 10.0.0.5

services:
  bitwarden:
    host: 10.0.0.2
    port: 7277
  home-assistant:
    host: 10.0.0.2
    port: 8122
    aliases:
      - homeassistant
  homer:
    host: 10.0.0.2
    port: 8081
  homer-remote:
    host: 10.0.0.2
    port: 8082
  pi-hole:
    host: 10.0.0.2
    port: 8080
    path: /admin/
    aliases:
      - pihole
  transmission:
    host: 10.0.0.61
    port: 9091
  prowlarr:
    host: 10.0.0.61
    port: 9696
  jackett:
    host: 10.0.0.61
    port: 9117
