authentik:
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-db-rw
    name: authentik

global:
  env:
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-db-app
          key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-db-app
          key: password
  envFrom:
    - secretRef:
        name: authentik-config

prometheus:
  rules:
    enabled: true

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: local-path
  volumePermissions:
    enabled: true

server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - authentik.linkvt.de
    paths:
      - "/"
    pathType: Prefix
  metrics:
    serviceMonitor:
      enabled: true
