authentik:
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-db-rw
    name: authentik

global:
  envFrom:
    - secretRef:
        name: authentik-config
  env:
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: db_username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: db_password

prometheus:
  rules:
    enabled: true

redis:
  enabled: true
  image:
    repository: bitnami/redis
    tag: 7.2.3-debian-11-r0
  master:
    persistence:
      existingClaim: authentik-app-data
      subPath: redis
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/bitnami-shell
      tag: 11-debian-11-r136

server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - authentik.oci.eduard-marbach.de
    paths:
      - "/"
    pathType: Prefix
  metrics:
    serviceMonitor:
      enabled: true
