authentik:
  error_reporting:
    enabled: true

envFrom:
  - secretRef:
      name: authentik-config

envValueFrom:
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: postgres
      key: postgresql-password

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: authentik.linkvt.de
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - authentik.linkvt.de
      secretName: authentik-certificate

postgresql:
  enabled: true
  existingSecret: postgres
  persistence:
    existingClaim: authentik-app-data
    subPath: postgres
  volumePermissions:
    enabled: true

prometheus:
  rules:
    create: true
  serviceMonitor:
    create: true

redis:
  enabled: true
  master:
    persistence:
      existingClaim: authentik-app-data
      subPath: redis
  volumePermissions:
    enabled: true
