authentik:
  error_reporting:
    enabled: true

envFrom:
  - secretRef:
      name: authentik

envValueFrom:
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: postgres
      key: postgresql-password

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
  hosts:
    - host: authentik.linkvt.de
      paths:
        - path: "/"
          pathType: Prefix

postgresql:
  enabled: true
  existingSecret: postgres
  persistence:
    existingClaim: authentik-app-data
    subPath: postgres
  volumePermissions:
    enabled: true

redis:
  enabled: true
  master:
    persistence:
      existingClaim: authentik-app-data
      subPath: redis
  volumePermissions:
    enabled: true
