authentik:
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-db-rw
    name: authentik

envFrom:
  - secretRef:
      name: authentik-config

envValueFrom:
  AUTHENTIK_POSTGRESQL__USER:
    secretKeyRef:
      name: authentik-db-app
      key: username
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: authentik-db-app
      key: password

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: authentik.linkvt.de
      paths:
        - path: "/"
          pathType: Prefix

prometheus:
  rules:
    create: true
  serviceMonitor:
    create: true

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      storageClass: local-path
  volumePermissions:
    enabled: true
