authentik:
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-db-rw
    name: authentik

envFrom:
  - secretRef:
      name: authentik-config

envValueFrom:
  AUTHENTIK_POSTGRESQL__USER:
    secretKeyRef:
      name: authentik-secrets
      key: db_username
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: authentik-secrets
      key: db_password

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: authentik.oci.eduard-marbach.de
      paths:
        - path: "/"
          pathType: Prefix

prometheus:
  rules:
    create: true
  serviceMonitor:
    create: true

redis:
  enabled: true
  image:
    repository: bitnami/redis
    tag: 7.2.3-debian-11-r0
  master:
    persistence:
      existingClaim: authentik-app-data
      subPath: redis
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/bitnami-shell
      tag: 11-debian-11-r136
