authentik:
  error_reporting:
    enabled: true
  postgresql:
    host: authentik-rw
    name: authentik

envFrom:
  - secretRef:
      name: authentik-config

envValueFrom:
  # POSTGRESQL_AUTHENTIK_PASSWORD: "{{ authentik.postgresqlAuthentikPassword }}"
  # POSTGRESQL_POSTGRES_PASSWORD: "{{ authentik.postgresqlPostgresPassword }}"
  AUTHENTIK_POSTGRESQL__USER:
    secretKeyRef:
      name: authentik-app
      key: username
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: authentik-app
      key: password

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: authentik.linkvt.de
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - authentik.linkvt.de
      secretName: authentik-certificate

prometheus:
  rules:
    create: true
  serviceMonitor:
    create: true

redis:
  enabled: true
  master:
    persistence:
      existingClaim: authentik-app-data
      subPath: redis
  volumePermissions:
    enabled: true
