apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
  monitoring:
    enablePodMonitor: true
  storage:
    pvcTemplate:
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
