apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  postgresql-password: "{{ authentik.postgresqlAuthentikPassword }}"
  postgresql-postgres-password: "{{ authentik.postgresqlPostgresPassword }}"
