apiVersion: v1
kind: Secret
metadata:
  name: authentik-config
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "{{ authentik.secretKey }}"
  AUTHENTIK_EMAIL__HOST: "{{ smtp.host }}"
  AUTHENTIK_EMAIL__PASSWORD: "{{ smtp.password }}"
  AUTHENTIK_EMAIL__PORT: "{{ smtp.port }}"
  AUTHENTIK_EMAIL__USERNAME: "{{ smtp.username }}"
  AUTHENTIK_EMAIL__USE_TLS: "{{ smtp.tls }}"
  AUTHENTIK_EMAIL__FROM: authentik <authentik@oci.eduard-marbach.de>
  #POSTGRESQL_AUTHENTIK_PASSWORD: "{{ authentik.postgresqlAuthentikPassword }}"
  #POSTGRESQL_POSTGRES_PASSWORD: "{{ authentik.postgresqlPostgresPassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
stringData:
  db_username: "{{ authentik.dbUsername }}"
  db_password: "{{ authentik.dbPassword }}"
