apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres
  namespace: authentik
spec:
  encryptedData:
    postgresql-password: AgAutQb+GJ4gfTiNS+rL/UwhbypQBEU+Bq731P9vqL9Y2VEayUEUSOivF9zZbqZfHvh0/FiE6xajCz/SVg5LB6IkIOiL2s0A0US801OoZat0eZebvG6PhNeHw6vJo2n6bqh9sV7VDAHI14U17rzuRWEBJH6rhUKhxzGtR4sog+83/fFnxgkRAlB6X4QBtMvXFcncYD08YhjYOAkGGWwGoa8yBTuQikhiMXmWXDzfUk1fxlEijsCNE9k+2Up3Do76IbTFCrQs3bzd0CIk1vzRrH941A/A6eaURB1rbsm8t0BoY0Iqqk+hUJaAezzV/ZPEEsOVaTdpaiHBWMsvbAHWG/2suH+M7fnv1IHEQSMPw/WCmF1vBiBaRjU8lXf+hUxX1WLIaT4hsdVc608TwRi1WBCwpe9dEitq7mI+/BbnOQsVcO0kNVud2aUNeUEloQ3q/62a01ROBIEkYv34UNIVwr9SN11Pbc2m1NZ1TSIcOLFfavZbHhkjGzLskAbfqChIBQGUpjZF4ZzFu4OsW8BaxU0E+eLlJ+LnyGV/zonxYO43xnIjm8TYmKzt0itLxO/wT/7OuFYwcY2a7vCm/x3NCu/WcmpXz3zdjRtdi/ACRpB6P/h472ng84oZtic+zYsP/7PJk2gufVZOFVFYD7oopTibhaKbGWkUsgaLedd3/agjJXKge24Zn75c3j0KB6HGDtdNnyInyuSsEETdCMgMibpWLtZdZCNqhwGFHogt+d0PIQ==
    postgresql-postgres-password: AgACQDGsZCxu7US4NaoZWBjF3CIon0UfxXoBlg15xWGJJ045BRHRKIw3kHHt9FiqesYm0Yr+cSQSP+PJxRycGCegbgoijrTjKdalSuhmMtb6Vit0ZuOkzmrA0GEkCAwQvMZTezQUnv1xdILiZAsDFR52TBsWHGaWmV/MzNOrJpeNazEVT/n5E6sEdGNxxx8RBDefDPKVmidfBnZnemTu8ex9aDmcT/7TLY/ge/L3QCKz9rPmX79mozFWPbVXALdv0k77a2N+QOKWf5EAdqS6TGZnUuXO49O5LSoUQmCPatyQwpqZMG9NPD8TS/f0inZjDKDDxaLUD//OoH6ZSnP+S2M+QZVQoEW4gw1/C8beZtTuBAJdbhTIG/vQMcnS8nO49o3XLf59aOOhjyMJ9KblwHWf4Fb2LEDhsvRCosl41osXZr6tMrXxB5E2z4xfGGy+4FavkXJUJqu8T2GWIfZ5FTio+VAK+RTGrK0pCdbWBFUNfNrbduwVg3Z0jQECjACeYJF1v1ymD+lOG8iuHPg2PnhD1C9+DJ+jvMvLGHIVGh7SJ3BWx8XMDQQ8HqR/yZTrnwAUpy8b9fvETf55bjpCAcl2cr+teg7uy+nvqi3EwR2ajJMgoWGNL5TxFTQ0yemyT2sOZ3jZ44zYQsI41eev0pKn1xfivOzepw1PCfDiIQQzCAHIw1pPRRpW59QkzsL7qEfIGzXd4AvBqflUYv6vZUmYBWqPt0XG0Z+5KAv+eo6Rmg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres
      namespace: authentik
    type: Opaque

