apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-app-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/indigo/apps/authentik"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-app-data
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: authentik-app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
