apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-rendered.yaml
  - namespace.yml
patches:
  - path: patch-kluctl-ignore-conflicts.yml
    target:
      name: kube-prometheus-kube-prome-admission
