creation_rules:
  - path_regex: secrets.yml
    key_groups:
      - age:
          - age1gznk0mzy2qse7sst2mauura0uj0at2pmg9rp2vudfxgu5jjp2gesekp76k # @linkvt
          - age1nl9v6l8rgz2xnwujjlwe0mqyzxw2pqgvukg8vd6lz7dyf0lx5sfs5w9mt3 # github actions
