creation_rules:
  - path_regex: secrets.yml
    key_groups:
      - age:
          - age1gznk0mzy2qse7sst2mauura0uj0at2pmg9rp2vudfxgu5jjp2gesekp76k # @linkvt
          - age14f5yjrr7fnvedcktkf0zc53c5v59n2cpd6cuvms0e0zf0qcpjp0qfvk497 # github actions
