name: Pulumi

on:
  pull_request:
    paths:
      - .github/workflows/pulumi.yml
      - pulumi/**
  push:
    paths:
      - .github/workflows/pulumi.yml
      - pulumi/**
  workflow_dispatch:

defaults:
  run:
    working-directory: pulumi

jobs:
  pulumi:
    name: Pulumi Preview and Up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pulumi/pnpm-lock.yaml

      - run: pnpm install

      - name: pulumi preview
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: prod
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: pulumi up
        if: github.ref == 'refs/heads/main'
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: prod
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
