apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-encrypt-wildcard
spec:
  commonName: "*.linkvt.de"
  dnsNames:
    - "*.linkvt.de"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-wildcard

---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: wildcard
spec:
  defaultCertificate:
    secretName: tls-wildcard
