apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-encrypt-wildcard
spec:
  commonName: "*.oci.eduard-marbach.de"
  dnsNames:
    - "*.oci.eduard-marbach.de"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-wildcard
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-encrypt-wildcard-staging
spec:
  commonName: "*.oci.eduard-marbach.de"
  dnsNames:
    - "*.oci.eduard-marbach.de"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: tls-wildcard-staging
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  defaultCertificate:
    secretName: tls-wildcard
