additionalArguments:
  - --api.insecure=true # required to access via k8s ingress
  - --entrypoints.web.http.redirections.entryPoint.priority=1000 # reduce prio to allow overwrite for http only (e.g. jellyfin)

deployment:
  replicas: 1
  additionalVolumes:
    - name: logs
      persistentVolumeClaim:
        claimName: traefik

logs:
  access:
    enabled: true
    filePath: "/var/log/traefik/access.log"
    fields:
      general:
        # -- Available modes: keep, drop, redact.
        defaultmode: keep
        # -- Names of the fields to limit.
        names:
          {}
          ## Examples:
          # ClientUsername: drop
      headers:
        # -- Available modes: keep, drop, redact.
        defaultmode: keep
        # -- Names of the headers to limit.
        names:
          {}
          ## Examples:
          # User-Agent: redact
          # Authorization: drop
          # Content-Type: keep

updateStrategy:
  type: Recreate
  rollingUpdate: null

ports:
  traefik:
    expose: true
  web:
    # https://docs.traefik.io/routing/entrypoints/#redirection
    redirectTo:
      port: websecure
    hostPort: 80
  websecure:
    hostPort: 443
    # Trust forwarded  headers information (X-Forwarded-*).
    forwardedHeaders:
      trustedIPs:
        # when using proxyProtocol use IPs from https://www.cloudflare.com/ips-v4
        # - 173.245.48.0/20
        # - 103.21.244.0/22
        # - 103.22.200.0/22
        # - 103.31.4.0/22
        # - 141.101.64.0/18
        # - 108.162.192.0/18
        # - 190.93.240.0/20
        # - 188.114.96.0/20
        # - 197.234.240.0/22
        # - 198.41.128.0/17
        # - 162.158.0.0/15
        # - 104.16.0.0/13
        # - 104.24.0.0/14
        # - 172.64.0.0/13
        # - 131.0.72.0/22
        - 100.78.243.2/32 # reverse proxy
    # proxyProtocol:
    #   trustedIPs:
    #     - 100.78.243.2/32 # reverse proxy (when traefik nodeport service has traffic policy local)
    #     - 10.0.0.4/32 # home server (when traefik nodeport service has traffic policy cluster)

service:
  annotations:
    metallb.universe.tf/allow-shared-ip: "main"

additionalVolumeMounts:
  - name: logs
    mountPath: /var/log/traefik
    subPath: logs
