apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - helm-rendered.yaml
  - default-certificate.yml
  - ingress.yml
  - namespace.yml
  - nodeport-service.yml
  - storage.yml
