apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - helm-rendered.yaml
  - ingress.yml
  - middleware-redirect-https.yml
  - namespace.yml
  - nodeport-service.yml
