apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/indigo/apps/traefik"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: traefik
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

