apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mosquitto.yml
  - storage.yml
configMapGenerator:
  - name: mosquitto-conf
    files:
      - mosquitto.conf
secretGenerator:
  - name: mosquitto-password-file
    files:
      - password_file
