apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
        - name: prepare-password-file
          image: eclipse-mosquitto:2.0.18
          command: ["sh", "-c"]
          args:
            - set -ex;
              cp /config/password_file /mosquitto/config/;
              chown 1883:1883 /mosquitto/config/password_file;
              chmod 700 /mosquitto/config/password_file;
              mosquitto_passwd -U /mosquitto/config/password_file;
          volumeMounts:
            - mountPath: /mosquitto/config
              name: app-data
              subPath: config
            - mountPath: /config/
              name: mosquitto-password-file
      containers:
        - name: mosquitto
          args:
            - "/usr/sbin/mosquitto"
            - "-c"
            - "/app/mosquitto.conf"
          image: eclipse-mosquitto:2.0.18
          livenessProbe:
            tcpSocket:
              port: mqtt
          readinessProbe:
            tcpSocket:
              port: mqtt
          ports:
            - name: http
              containerPort: 9001
            - name: mqtt
              containerPort: 1883
          volumeMounts:
            - mountPath: /mosquitto/config
              name: app-data
              subPath: config
            - mountPath: /app/mosquitto.conf
              name: mosquitto-conf
              subPath: mosquitto.conf
            - mountPath: /mosquitto/data
              name: app-data
              subPath: data
            - mountPath: /mosquitto/log
              name: app-data
              subPath: log
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: mosquitto-local
        - name: mosquitto-conf
          configMap:
            name: mosquitto-conf
        - name: mosquitto-password-file
          secret:
            secretName: mosquitto-password-file

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
    - port: 1883
      name: mqtt
      targetPort: mqtt
  selector:
    app: mosquitto

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: main
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      name: mqtt
      targetPort: mqtt
  selector:
    app: mosquitto
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mosquitto
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt
#     traefik.ingress.kubernetes.io/router.middlewares: authentik-auth@kubernetescrd
# spec:
#   rules:
#     - host: mosquitto.linkvt.de
#       http:
#         paths:
#           - pathType: Prefix
#             path: /
#             backend:
#               service:
#                 name: mosquitto
#                 port:
#                   name: http
