apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-app-data
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/apps/mosquitto"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-app-data
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: mosquitto-app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
