- name: Install torrent packages
  apt:
    pkg:
      - rtorrent
    state: latest
    update_cache: true

- name: Uninstall removed packages
  apt:
    pkg:
      - transmission
    state: absent
    purge: true
    autoremove: true
