apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - helm-rendered.yaml
  - namespace.yml
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v1.20.2/docs/src/samples/monitoring/grafana-configmap.yaml
