apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      volumes:
        - name: media
          hostPath:
            type: Directory
            path: /data/media/all/movies/The Menu (2022)
      containers:
        - name: caddy
          image: caddy:2.6.4
          args:
            - caddy
            - file-server
            - --browse
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: /srv
              name: media

---
apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: caddy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: share-basic-auth@kubernetescrd
spec:
  rules:
    - host: share.linkvt.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: caddy
                port:
                  name: http
  tls:
    - hosts:
        - share.linkvt.de
      secretName: share-certificate
