---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jelly-trakt-hook
spec:
  selector:
    matchLabels:
      app: jelly-trakt-hook
  template:
    metadata:
      labels:
        app: jelly-trakt-hook
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: media-app-data
      containers:
        - name: jelly-trakt-hook
          image: blackdark93/dockerfiles-jellyfin-trakt-hook:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5001
          envFrom:
            - configMapRef:
                name: common-deployment-environment
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: trakt-credentials
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: trakt-credentials
                  key: clientSecret
            - name: CONFIG_DIR
              value: "/config"
          volumeMounts:
            - mountPath: /config
              name: app-data
              subPath: trakt-syncer
---
apiVersion: v1
kind: Secret
metadata:
  name: trakt-credentials
stringData:
  clientId: "{{ trakt.clientId }}"
  clientSecret: "{{ trakt.clientSecret }}"
---
apiVersion: v1
kind: Service
metadata:
  name: jelly-trakt-hook
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: jelly-trakt-hook
---

