apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - config.yml
  - jackett.yml
  - jellyfin.yml
  - lidarr.yml
  - namespace.yml
  - prowlarr.yml
  - radarr.yml
  - readarr.yml
  - sabnzbd.yml
  - sonarr.yml
  - storage-app.yml
  - storage-media.yml
