apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
spec:
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: media-app-data
        - name: media
          persistentVolumeClaim:
            claimName: media-downloads
      containers:
        - name: readarr
          image: ghcr.io/linuxserver/readarr:develop-0.1.1.1526-ls28
          ports:
            - name: http
              containerPort: 8787
          envFrom:
            - configMapRef:
                name: common-deployment-environment
          volumeMounts:
            - mountPath: /config
              name: app-data
              subPath: readarr
            - mountPath: /data
              name: media

---
apiVersion: v1
kind: Service
metadata:
  name: readarr
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: readarr

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readarr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: authentik-auth@kubernetescrd
spec:
  rules:
    - host: readarr.linkvt.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: readarr
                port:
                  name: http
  tls:
    - hosts:
        - readarr.linkvt.de
      secretName: readarr-certificate
