apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: media-app-data
        - name: media
          persistentVolumeClaim:
            claimName: media-downloads
      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd:4.2.2-ls147
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: common-deployment-environment
          volumeMounts:
            - mountPath: /config
              name: app-data
              subPath: sabnzbd
            - mountPath: /downloads
              name: media
              subPath: usenet/
            - mountPath: /incomplete-downloads
              name: media
              subPath: usenet/_incomplete
            - mountPath: /data
              name: media

---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: sabnzbd

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-basic
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: media-basic-auth@kubernetescrd
spec:
  rules:
    - host: sabnzbd-basic.oci.eduard-marbach.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sabnzbd
                port:
                  name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: authentik-auth@kubernetescrd
spec:
  rules:
    - host: sabnzbd.oci.eduard-marbach.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sabnzbd
                port:
                  name: http
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sabnzbd-local
# spec:
#   storageClassName: local-path
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

# kubectl -n media exec -it sabnzbd-86d6bf7f84-fqkr9 -- bash -c 'sed -i -e "s/^host_whitelist *=.*$/host_whitelist = ${HOSTNAME},sabnzbd.oci.eduard-marbach.de,sabnzbd,sabnzbd.media /g" /config/sabnzbd.ini'
# kubectl -n media exec -it prowlarr-6cff74cbbb-4bg9s -- bash -c 'sed -i -e "s/^  <AuthenticationMethod>None<\/AuthenticationMethod>$/  <AuthenticationMethod>External<\/AuthenticationMethod>/g" /config/config.xml'
