apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-app-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/apps"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-app-data
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: media-app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
