apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/media"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: media-downloads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
