apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored
spec:
  template:
    spec:
      containers:
        - name: flux-kluctl-controller
          volumeMounts:
            - mountPath: /.cache
              name: cache
      volumes:
        - emptyDir: {}
          name: cache
