apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-config-{{ load_sha256("dnsmasq-configmap.yml") }}
data:
  02-custom.conf: |
    address=/linkvt.de/10.0.0.5
    address=/h.linkvt.de/10.0.0.5

    # Block IPv6 responses for *.linkvt.de
    address=/linkvt.de/::

    # Set specific DNS servers for www.linkvt.de
    server=/www.linkvt.de/1.1.1.1
    server=/www.linkvt.de/8.8.8.8
