apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
spec:
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: pi-hole-local
        - name: dnsmasq-config
          configMap:
            name: dnsmasq-config-{{ load_sha256("dnsmasq-configmap.yml") }}
      containers:
        - name: pi-hole
          image: ghcr.io/pi-hole/pihole:2024.02.0
          ports:
            - name: http
              containerPort: 80
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Berlin
            - name: VIRTUAL_HOST
              value: pi-hole.linkvt.de
          livenessProbe:
            httpGet:
              path: /admin/index.php
              port: http
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /admin/index.php
              port: http
            failureThreshold: 10
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/pihole
              name: app-data
              subPath: pihole
            - mountPath: /etc/dnsmasq.d
              name: app-data
              subPath: dnsmasq.d
            - mountPath: /etc/dnsmasq.d/02-dnsmasq.conf
              name: dnsmasq-config
              subPath: 02-custom.conf

---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: pi-hole

---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole-dns
  annotations:
    metallb.universe.tf/address-pool: dns
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      name: udp
      protocol: UDP
      targetPort: dns-udp
    - port: 53
      name: tcp
      protocol: TCP
      targetPort: dns-tcp
  selector:
    app: pi-hole

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-hole
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: authentik-auth@kubernetescrd
spec:
  rules:
    - host: pi-hole.linkvt.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pi-hole
                port:
                  name: http
