apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi-hole-app-data
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/apps/pi-hole"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-app-data
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pi-hole-app-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
