prometheus:
  namespace: monitoring
  podMonitor:
    enabled: true
  prometheusRule:
    enabled: true
    addressPoolUsage:
      enabled: false
  serviceAccount: kube-prometheus-kube-prome-prometheus
