apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - helm-rendered.yaml
  - address-pool.yml
  - namespace.yml
  - l2-advertisement.yml
patches:
  - path: patch-kluctl-ignore-conflicts.yml
    target:
      kind: CustomResourceDefinition
      name: "^(addresspools|bgppeers).*"
