- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest
    update_cache: true

- name: Autostart fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Copy fail2ban files
  when: item.state == 'file'
  with_community.general.filetree: "{{ 'templates/' }}"
  template:
    src: "{{ item.src }}"
    dest: "/{{ item.path | replace('.j2', '') }}"
    owner: root
    group: root
    mode: "0600"
    backup: true
  notify:
    - Restart fail2ban
