- name: Create fail2ban base directory
  file:
    path: "{{ fail2ban_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create fail2ban container config directory
  file:
    path: "{{ fail2ban_container_config_dir }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Create fail2ban subdirectories
  when: item.state == 'directory'
  with_community.general.filetree: "{{ 'templates/' }}"
  file:
    path: "{{ fail2ban_container_config_dir }}/{{ item.path }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Copy fail2ban files
  when: item.state == 'file'
  with_community.general.filetree: "{{ 'templates/' }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ fail2ban_container_config_dir }}/{{ item.path | replace('.j2', '') }}"
    owner: 1000
    group: 1000
    mode: "0600"
  register: fail2ban_configuration

- name: Start the fail2ban container
  docker_container:
    name: fail2ban
    image: lscr.io/linuxserver/fail2ban:1.0.2-r2-ls29
    network_mode: host
    restart: "{{ fail2ban_configuration.changed }}"
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Berlin
    volumes:
      - "{{ fail2ban_container_dir }}:/config"
      - "/var/log:/var/log:ro"
    capabilities:
      - NET_ADMIN
      - NET_RAW
