apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - helm-rendered.yaml
  - lets-encrypt-production.yml
  - lets-encrypt-staging.yml
  - namespace.yml
  - prometheus-alerts.yml
