- name: Create the resolved.conf dropin directory
  file:
    state: directory
    path: /etc/systemd/resolved.conf.d
    owner: root
    group: root
    mode: "0700"

- name: Copy the systemd resolved drop in
  copy:
    src: resolved-pihole.conf
    dest: /etc/systemd/resolved.conf.d/pihole.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart systemd-resolved

- name: Create the config directory
  file:
    state: directory
    path: "{{ pihole_config_dir }}"
    owner: root
    group: root
    mode: "0700"

- name: Start the pihole container
  docker_container:
    name: pihole
    image: pihole/pihole:2022.09.3
    restart_policy: unless-stopped
    ports:
      - 10.0.0.2:53:53/tcp
      - 10.0.0.2:53:53/udp
      - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
      - 8080:80/tcp
      - 8443:443/tcp
    env:
      VIRTUAL_HOST: "{{ ansible_hostname }}"
      TZ: Europe/Berlin
    dns_servers:
      - 127.0.0.1
      - 1.1.1.1
    capabilities:
      - NET_ADMIN
    volumes:
      - "{{ pihole_config_dir }}/pihole:/etc/pihole"
      - "{{ pihole_config_dir }}/dnsmasq.d:/etc/dnsmasq.d"
