apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
