deployments:
  - path: authentik
  - path: cert-manager
  - path: default
  - path: media
  - path: metallb
  - path: pi-hole
  - path: sealed-secrets
  - path: traefik

commonLabels:
  de.linkvt/stack: home-server
