commonLabels:
  de.linkvt/stack: home-server

deployments:
  - path: kube-system
  - path: local-path-provisioner
  - barrier: true # storage is required by many apps
  - path: monitoring
  - barrier: true # prometheus CRDs are required to deploy the apps
  - path: authentik
  - path: bitwarden
  - path: cert-manager
  - path: cnpg-system
  - path: default
  - path: fluxcd
  - path: k8up
  - path: media
  - path: metallb
  - path: pi-hole
  - path: smart-home
  - path: traefik
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      ref:
        # renovate: datasource=github-tags depName=kluctl/kluctl
        tag: v2.23.2

vars:
  - file: secrets.yml
