commonLabels:
  de.linkvt/stack: home-server

deployments:
  - path: authentik
  - path: cert-manager
  - path: default
  - path: media
  - path: metallb
  - path: monitoring
  - path: pi-hole
  - path: sealed-secrets
  - path: traefik

vars:
  - clusterSecret:
      name: smtp-credentials
      namespace: default
      key: vars
