commonLabels:
  de.linkvt/stack: home-server

deployments:
  - path: authentik
  - path: bitwarden
  - path: cert-manager
  - path: default
  - path: flux-kluctl-controller
  - path: fluxcd
  - path: k8up
  - path: kube-system
  - path: media
  - path: metallb
  - path: monitoring
  - path: pi-hole
  - path: smart-home
  - path: share
  - path: traefik

vars:
  - file: secrets.yml
