age:
    ci_key: ENC[AES256_GCM,data:55zJ7DW5QRumAOrS33x8V7L9btByF6QuBeBGBsiDzYCZUwN4GYsF46QPSNfDYwftHidWN6H+uSOr6zv3EcbYcz+NDxvQ61fUPD8=,iv:IA19JXbodk3fHeuR9S/K+ATlgbYKKBkqVjaLv14QQQM=,tag:c0vQrQvFw77OztIlG4i/6g==,type:str]
authentik:
    secretKey: ENC[AES256_GCM,data:u3PVNdAlyggyV39y1Mffb7F7AjE2luYDEL3ktA+5lA==,iv:Yz+S7j8RD44Mg1RrBE/DvFqDyAhB8VGzvKTbprQGutM=,tag:54lPbGaMChnf1udo3Xz+YA==,type:str]
    postgresqlAuthentikPassword: ENC[AES256_GCM,data:L9NJD338M7eR3RyuydkoextroLiRPUo/nWkXN/7wqw==,iv:OWSFuLNe9D6T7C72UTalhoA/ugUs/BCJi4K2fpijofA=,tag:dd67Rtv6lSxLjchk9Ld31A==,type:str]
    postgresqlPostgresPassword: ENC[AES256_GCM,data:wUm79XTP//VW9THWAA31ow4yNabDKZLzivmF/u8q4Q==,iv:q6o2Et5xUy7IhE2t/Lkr/4fK2VH8cdJK/vRzlK6Cm8s=,tag:EFGoRRWOa561eXO6ovV56A==,type:str]
    dbUsername: ENC[AES256_GCM,data:roVk/xYhWdNb,iv:BC+ltj4Yw9yd8Z/H78LaGgk/xY+k34wmUh+S4TCFCCE=,tag:Bms9vK0tYmbHyB/Rnrw2Zg==,type:str]
    dbPassword: ENC[AES256_GCM,data:GZnx7g6L8IErgN4FU8cgV9co2JbbLdpnz0XTgT0kt6S1RR4GCxsqknVK/4nOVdZSwYB3IlurjgrRgoGGu5Z/zw==,iv:9I1D+jjXstNlx4ln5OUT5k2ikBqNXy3s8eisjIRwOjU=,tag:42sjgsvBqgNwA++9fD6Glw==,type:str]
auth:
    media:
        username: ENC[AES256_GCM,data:WIMYFw==,iv:MO/hw8Lif0+Ia/aYb++ab/g4aUWxMQrYP+hi3LSaV34=,tag:2zekBpXBiygcxQfi/FIq4g==,type:str]
        password: ENC[AES256_GCM,data:sMRQtebCznH7hwaj+ZrmdqJhPkv9DB1OxYAQ,iv:QwbGh32zdK9DGB+E+K5uufz2eMbGiZINnWTxGIT1xks=,tag:AFFLjz8uRfxIIHEFN7FLNw==,type:str]
flux:
    credentials:
        username: ""
        password: ""
mosquitto:
    auth:
        homeassistant: ""
        tasmota: ""
        zigbee2mqtt: ""
smtp:
    host: ENC[AES256_GCM,data:zmPfWFNIZdhlec1XHVfZUeY=,iv:CS+1caRKgGlqjdHBoxExBYd+bR3uZ2LzYrcgh6gZ41s=,tag:Kw/k+FeN62M4FNhDliLrIA==,type:str]
    port: ENC[AES256_GCM,data:+Ubb,iv:Amk1BnSrzfSk9LHKeAEmHTZzi+UNrQUX6eMnbyWkAi0=,tag:G+d3lo9zNqbhchwqFhe0Kg==,type:str]
    username: ENC[AES256_GCM,data:1R4GBt5k,iv:2c4qsnqVoAawldnP6k7FbDEPxblScjpIszrIXs3puS8=,tag:6uDH4zi2WInwSVI0HQzjSg==,type:str]
    password: ENC[AES256_GCM,data:hLDj4sdubEwITZyyAEHHSNC+BxBxbhYQrhVZoECEyHymyitkNN92J889AC+gf3lf7DNBfXJKahZIDh0TdrGhex2NA0ta,iv:6iJmqb0B40cVkF0K+3syK1vMV3xSEBb0WT0XM2Yvkv4=,tag:kd1IJnVnT0fUqSLBokcGrQ==,type:str]
    tls: ENC[AES256_GCM,data:tD+63Q==,iv:3H4oCRennBKpswMRzQZ24GhrS47rqiEsRb6HcoLrbtk=,tag:xj5lb8Dae6yHbf1EgojTYg==,type:str]
letsEncrypt:
    cloudflareApiToken: ENC[AES256_GCM,data:YyBUAw/YKnTIkx3uv4n9cmVaHRbqvP6s0PuschYVbzEkaEgKaNrikw==,iv:I3B545q0ECbzjVthqaFYNdiNOTAPwR2sRa4nrRT/nNA=,tag:Gq46kYC5cCuydRHWL6UBlQ==,type:str]
trakt:
    clientId: ENC[AES256_GCM,data:ls1G5B8Nt3XKx8lXgqWuTy4CKTRUPA4AyDBQwk5ImkvhEQ6XcdjJiETsFXKoiMFBne9cf6eIvv0c2ljQxEKlLA==,iv:Su3lzqSUVXpaWA7gvc5W9dqtFawZAq9PncECAHNP/VU=,tag:nfEq4hxMiEmsRxuH8sar8A==,type:str]
    clientSecret: ENC[AES256_GCM,data:jWU0FELcFFi5liZbnf1BSETLEYoo9IoUmdPCxFreUdiEscdk/vQyq1SSN3/LNbDZQ8u8daQcMHcIJ52Nw3KwyQ==,iv:1BZMAAHxnxde9Wx9LWxp8G/2xaQUdMFn0ioGUItLJVQ=,tag:6nmpEahPtUkE4bddoVcuVA==,type:str]
recyclarr:
    sonarrApiKey: ENC[AES256_GCM,data:+rICtGRMgpNj4iwZ1X1mMzBrgWy4ybeyeETpKW4ONr0=,iv:cdsjcFFwgNRh4ey2vsaC5q3hsCFA1sKSAoxP3kBaCyo=,tag:/lqUaDaGJ4Is572lzIzs2w==,type:str]
    sonarrAnimeApiKey: ENC[AES256_GCM,data:U1m47lu6V51wMHwTK7UhiCca4FaxTYn55CI4F4Ubals=,iv:FwtvSS7I49/N/XwTQGlLxHYXAQZ1eEFIFPwJiP34BDA=,tag:J/RTJC3spPUVniDgLubpQw==,type:str]
    radarrApiKey: ENC[AES256_GCM,data:k2lpWbLn9MGiF/8WjsvMbvfngf2458WpMq185QSSwC0=,iv:t5elsw0HYflQyJWlMzUqnAiqE4yMP7YnWHdaQiVuT4Q=,tag:MOX++F0zgZAXDDbEVU8YlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ymaq7pzv2j0rqejhkvq5kuu350yddg27lc3md9y6pvckdzl8cuvsc4akj5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbHhldFFUcWxDTTdnU292
            WjZUdENXcWtwMmhPYm1OekRPdmNDQ0ZpVENvCjRZdVQxSHZPVkVKVUdWajdoZisr
            L09aM0N6ZFM4SzZwSVpPTEVPS3BXRWsKLS0tIFdWaDJXbi9nL3EzK29NOWhHSFZr
            cTJaOUxUa0Fod2hHcUN3NWNtbkxuSE0KdNx9uSJ+MM6TVoFNuxIkh3UNnfOCwV4B
            TPFmeW5z28nlGjoNO3G11955NxtkXDZoN3RpiY1dfATBvqlp9BjDkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T13:04:35Z"
    mac: ENC[AES256_GCM,data:6nghEyW3y7jJ0Ynlgnk7okJnWD0uAUkrhYvV/gdv/ktbmrOqYkT1DI22l4hoWc5l8SHXJYVkzyCv1azsO+4H5xt5vnUPloIb0oqsxTP8fxqbUn0NnUuNe2Us0lhO4HghGcmMDKtwner+lxFGDW/N709tsW/YyiRtAenuCLb4CRY=,iv:MyjkrrDk09a8DzWLmPVdFunUopHVX5vENwZwbQh/3pg=,tag:lDHuGpUfeiZULResYhOVIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
