---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
spec:
  ports:
    - port: 80
      name: http
      targetPort: 7277

---
apiVersion: v1
kind: Endpoints
metadata:
  name: bitwarden
subsets:
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 7277
        name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
spec:
  rules:
    - host: bitwarden.linkvt.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: bitwarden
                port:
                  name: http
