---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8122

---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
subsets:
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 8122
        name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: home-assistant-old.linkvt.de
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: home-assistant
                port:
                  name: http
  tls:
    - hosts:
        - home-assistant-old.linkvt.de
      secretName: home-assistant-certificate
