all:
  hosts:
    v21904.1blu.de:
      ansible_user: root
  children:
    raspberrypi:
      hosts:
        raspi-seedbox:
          ansible_host: 10.0.0.61 # home network
          # ansible_host: 100.88.215.99 # tailscale
          ansible_user: root
        raspi-home:
          ansible_host: 10.0.0.2 # home network
          # ansible_host: 100.91.165.113 # tailscale
          ansible_user: root
