all:
  hosts:
    v21904.1blu.de:
      ansible_user: root
  children:
    raspberrypi:
      hosts:
        raspy-seedbox:
          ansible_become: true
          ansible_host: 100.88.215.99
          ansible_user: root
          docker_compose_arch: aarch64
          docker_apt_arch: arm64
