- hosts: raspi-home
  roles:
    - base
    - tailscale
    - geerlingguy.docker
    - homeassistant
    - role: caddy
      tags: caddy
    - role: homer
      tags: homer
      homer_message: local
    - role: homer
      tags: homer
      homer_message: vpn
      homer_instance: homer-remote
      homer_port: 8082 # see group_vars/all
      homer_load_balancer_ip: 100.91.165.113 # see group_vars/all
