- hosts: v21904.1blu.de
  roles:
    - base
    - fail2ban
    - role: geerlingguy.docker
      vars:
        docker_daemon_options:
          log-driver: "local"

    - role: traefik
      tags: traefik
