apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: infrastructure
spec:
  credentials:
    git:
      - host: github.com
        path: linkvt/*
        secretRef:
          name: infrastructure-git-credentials
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  # dryRun: true
  interval: 60m
  prune: true
  source:
    git:
      url: https://github.com/linkvt/infrastructure.git
      path: kubernetes
  timeout: 5m
