apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-rendered.yaml
  - kluctl-deployment.yml
  - namespace.yml
  - secret-git-credentials.yml
  - secret-sops-keys.yml
