apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zigbee2mqtt.yml
  - storage.yml
configMapGenerator:
  - name: zigbee2mqtt-initial-config
    files:
      - configuration.yml
