annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: upgrade to authentik 2023.2.3
  artifacthub.io/images: |
    - name: authentik
      image: ghcr.io/goauthentik/server:2023.2.3
      whitelisted: true
    - name: authentik-outpost-proxy
      image: ghcr.io/goauthentik/proxy:2023.2.3
      whitelisted: true
    - name: authentik-outpost-ldap
      image: ghcr.io/goauthentik/ldap:2023.2.3
      whitelisted: true
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Github
      url: https://github.com/goauthentik/authentik
    - name: Docs
      url: https://goauthentik.io/docs/
  artifacthub.io/maintainers: |
    - name: authentik Team
      email: hello@goauthentik.io
      url: https://goauthentik.io
  artifacthub.io/screenshots: |
    - title: User interface
      url: https://goauthentik.io/img/screen_apps_light.jpg
    - title: Admin interface
      url: https://goauthentik.io/img/screen_admin_light.jpg
apiVersion: v2
appVersion: 2023.2.3
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.goauthentik.io
  version: 10.16.2
- condition: redis.enabled
  name: redis
  repository: https://charts.goauthentik.io
  version: 15.7.6
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.2.0
description: authentik is an open-source Identity Provider focused on flexibility
  and versatility
home: https://goauthentik.io
icon: https://goauthentik.io/img/icon.png
keywords:
- proxy
- oauth
- authentication
- saml
- sso
- identity
- single-sign-on
- ldap
- idp
- sp
maintainers:
- email: hello@goauthentik.io
  name: authentik Team
  url: https://goauthentik.io
name: authentik
sources:
- https://goauthentik.io/docs/
- https://github.com/goauthentik/authentik
version: 2023.2.4
