apiVersion: v1
kind: PersistentVolume
metadata:
  name: crowdsec-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/indigo/apps/crowdsec/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-data
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: crowdsec-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crowdsec-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/indigo/apps/crowdsec/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-config
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: crowdsec-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
