seedbox_vpn_container_name: nordvpn

seedbox_p2p_base_dir: /data/p2p
seedbox_p2p_config_dir: "{{ seedbox_p2p_base_dir }}/config"

seedbox_downloads_dir: "{{ seedbox_p2p_base_dir }}/downloads"
seedbox_watch_dir: "{{ seedbox_p2p_base_dir }}/watch"
