- name: Create homer config directory
  file:
    path: "{{ homer_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create homer subdirectories
  when: item.state == 'directory'
  with_community.general.filetree: "{{ 'files/' }}"
  file:
    path: "{{ homer_config_dir }}/{{ item.path }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Copy homer files
  when: item.state == 'file'
  with_community.general.filetree: "{{ 'files/' }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ homer_config_dir }}/{{ item.path | replace('.j2', '') }}"
    owner: root
    group: root
    mode: "0644"

- name: Copy homer config
  template:
    src: "{{ item }}"
    dest: "{{ homer_config_dir }}/{{ item | replace('.j2', '') }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - config.yml.j2

- name: Start the homer container
  docker_container:
    name: "{{ homer_instance }}"
    image: b4bz/homer:v22.10.2
    restart_policy: unless-stopped
    ports:
      - 0.0.0.0:{{ homer_port }}:8080
    volumes: # mount the paths explicitly to not overwrite the icons folder
      - "{{ homer_config_dir }}/tools:/www/assets/tools"
      - "{{ homer_config_dir }}/config.yml:/www/assets/config.yml"
